connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: foodBase
  password: poli2015

connection: &sliqte
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *sliqte
  database: development#my_database_development

test:
  <<: *sliqte
  database: test#my_database_test

production:
  <<: *connection
  database: my_database_production