connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

connection: &sliqte
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *connection
  database: my_database_development

test:
  <<: *connection
  database: my_database_test

production:
  <<: *connection
  database: my_database_production